### PR TITLE
86: [BUG] Logger customisation is missing

### LINKED ISSUE #86: [BUG] Logger customisation is missing
Please add the necessary Logger customisation that is missing. NestJS doc: https://docs.nestjs.com/techniques/logger

- [ ] Make `colors` value configurable via an env variable. Having this set to `true` can result in log display issues when deployed.
- [ ] Make `logLevels` configurable via an env variable.
- [ ] Update docker compose and env example files.
- [ ] Do this for both Server and Agent.

### PR DESCRIPTION
**Pull request by furqattrade**
[ticket](https://devtailor.atlassian.net/jira/software/c/projects/BD/boards/240?selectedIssue=BD-43)

### CODE REVIEW

File: apps/dmr-agent/src/main.ts [hunk 1]
```diff
@@ -7,21 +7,34 @@ import { AppModule } from './app.module';
...
 
 async function bootstrap(): Promise<void> {
-  const app = await NestFactory.create<NestExpressApplication>(AppModule, { cors: true });
-  app.use(compression());
-  app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true }));
+  const logger = new ConsoleLogger('DMR-Agent', {
+    logLevels: (process.env.LOGGER_LOG_LEVELS?.split(',') as LogLevel[]) || [
+      'error',
+      'warn',
+      'log' as LogLevel,
```
Comment (IgorKrupenja) [inline apps/dmr-agent/src/main.ts]: I do not think you need `as LogLelvel` cast here.

File: apps/dmr-agent/src/main.ts [hunk 2]
```diff
@@ -7,21 +7,34 @@ import { AppModule } from './app.module';
 import { APP_CONFIG_TOKEN, AppConfig, GlobalConfig } from './common/config';
 
 async function bootstrap(): Promise<void> {
-  const app = await NestFactory.create<NestExpressApplication>(AppModule, { cors: true });
-  app.use(compression());
-  app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true }));
+  const logger = new ConsoleLogger('DMR-Agent', {
```
Comment (IgorKrupenja) [inline apps/dmr-agent/src/main.ts]: Please remove `DMR-Agent`, it is redundant.

File: apps/dmr-server/src/main.ts [hunk 3]
```diff
@@ -9,25 +9,38 @@ import { APP_CONFIG_TOKEN, AppConfig, GlobalConfig } from './common/config';
 import { handlers } from './mocks/handlers/centops.response';
 
 async function bootstrap(): Promise<void> {
-  const app = await NestFactory.create<NestExpressApplication>(AppModule, { cors: true });
-
-  app.use(compression());
-  app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true }));
+  const logger = new ConsoleLogger('DMR-Server', {
```
Comment (IgorKrupenja) [inline apps/dmr-server/src/main.ts]: Please remove `DMR-Server`, it is redundant.

File: apps/dmr-server/src/main.ts [hunk 4]
```diff
@@ -9,25 +9,38 @@ import { APP_CONFIG_TOKEN, AppConfig, GlobalConfig } from './common/config';
...
+    logLevels: (process.env.LOGGER_LOG_LEVELS?.split(',') as LogLevel[]) || [
+      'error',
+      'warn',
+      'log' as LogLevel,
```
Comment (IgorKrupenja) [inline apps/dmr-server/src/main.ts]: I do not think you need `as LogLelvel` cast here.

File: apps/dmr-agent/src/main.ts [hunk 5]
```diff
@@ -7,21 +7,34 @@ import { AppModule } from './app.module';
...
 
   await app.listen(appConfig.port);
 
   if (appConfig.environment === 'development') {
-    const logger = new Logger('bootstrap');
     logger.log(`Listening on ${await app.getUrl()}`);
   }
 
-  Logger.log(`🚀 Application is running on: http://localhost:${appConfig.port}`);
+  logger.log(`🚀 Application is running on: http://localhost:${appConfig.port}`);
```
Comment (IgorKrupenja) [inline apps/dmr-agent/src/main.ts]: This is an old leftover, let's remove it. We have `logger.log(`Listening on ${await app.getUrl()}`)` above anyway.

File: apps/dmr-server/src/main.ts [hunk 6]
```diff
@@ -9,25 +9,38 @@ import { APP_CONFIG_TOKEN, AppConfig, GlobalConfig } from './common/config';
...
   if (appConfig.environment === 'development') {
-    const logger = new Logger('bootstrap');
     logger.log(`Listening on ${await app.getUrl()}`);
 
     const server = setupServer(...handlers);
     server.listen();
   }
 
-  Logger.log(`🚀 Application is running on: http://localhost:${appConfig.port}`);
+  logger.log(`🚀 Application is running on: http://localhost:${appConfig.port}`);
```
Comment (IgorKrupenja) [inline apps/dmr-server/src/main.ts]: This is an old leftover, let's remove it. We have `logger.log(`Listening on ${await app.getUrl()}`)` above anyway.

File: apps/dmr-agent/src/common/config/app.config.ts [hunk 7]
```diff
@@ -10,10 +11,16 @@ const variables = Utils.validateObject(
   {
     port: Number(process.env.PORT),
     environment: process.env.ENVIRONMENT as Environment,
+    logLevels: (process.env.LOGGER_LOG_LEVELS?.split(',') as LogLevel[]) || undefined,
```
Comment (IgorKrupenja) [inline apps/dmr-agent/src/common/config/app.config.ts]: To be a bit more consistent, I suggest renaming this to `loggerLogLevels`.

File: apps/dmr-server/src/common/config/app.config.ts [hunk 8]
```diff
@@ -11,11 +12,17 @@ const variables = Utils.validateObject(
     port: Number(process.env.PORT),
     environment: process.env.ENVIRONMENT as Environment,
     websocketMaxDuration: Number(process.env.WEB_SOCKET_MAX_DISCONNECTION_DURATION),
+    logLevels: (process.env.LOGGER_LOG_LEVELS?.split(',') as LogLevel[]) || undefined,
```
Comment (IgorKrupenja) [inline apps/dmr-server/src/common/config/app.config.ts]: To be a bit more consistent, I suggest renaming this to `loggerLogLevels`.

**Review by IgorKrupenja — CHANGES_REQUESTED** [review]

**Review by IgorKrupenja — APPROVED** [review]
