### PR TITLE
[BUG] "CentOps configuration is empty" leads to dropped agent connections #139

### LINKED ISSUE #139: [BUG] "CentOps configuration is empty" leads to dropped agent connections
1. Run `docker compose up`.

Occasionally (but not 100%) you will get this in logs:

- First, "Error while get response from http://localhost:3000/centops/clients". 
- Then, "CentOps configuration is empty".
- The agent connections are closed because of this error.
- The Agent does **not** try to re-connect.
 
Can this be caused by some race condition? E.g. an agent connects before we got configuration from CentOps. This is possible in real life too when the solution is deployed. Consider this: Kubernetes restarts a DMR server pod and DMR agent attempts re-connection before we have agent config.

- [ ] Please find a way to handle this more gracefully.
- [ ] Please also investigate why `http://localhost:3000/centops/clients` request is failing in the first place. Is this related to MSW?

**Workaround**: Restart DMR agent containers.

```log
dmr-server    | [Nest] 1  - 07/03/2025, 12:30:14 PM   ERROR [CentOpsService] CentOps configuration is empty +623ms
dmr-server    | [Nest] 1  - 07/03/2025, 12:30:14 PM   ERROR [AgentGateway] Error during agent socket connection: RQ8rIvyWCixCOTNiAAAB - CentOps configuration is empty +1ms
dmr-server    | AgentGateway
dmr-server    | [Nest] 1  - 07/03/2025, 12:30:14 PM     LOG [AgentGateway] Agent disconnected: undefined (Socket ID: RQ8rIvyWCixCOTNiAAAB) +1ms
dmr-agent-a   | [Nest] 1  - 07/03/2025, 12:30:14 PM     LOG [WebsocketService] Connected to DMR server with ID: RQ8rIvyWCixCOTNiAAAB +731ms
dmr-agent-a   | [Nest] 1  - 07/03/2025, 12:30:14 PM     LOG [WebsocketService] Recovery state: new connection +0ms
dmr-agent-a   | [Nest] 1  - 07/03/2025, 12:30:14 PM    WARN [WebsocketService] Disconnected from DMR server. Reason: io server disconnect +2ms
dmr-server    | [Nest] 1  - 07/03/2025, 12:30:14 PM     LOG [AgentGateway] Agent disconnected: undefined (Socket ID: PDU6755A2sHMr9POAAAE) +0ms
dmr-server    | [Nest] 1  - 07/03/2025, 12:30:14 PM   ERROR [CentOpsService] CentOps configuration is empty +196ms
dmr-server    | [Nest] 1  - 07/03/2025, 12:30:14 PM   ERROR [AgentGateway] Error during agent socket connection: PDU6755A2sHMr9POAAAE - CentOps configuration is empty +0ms
dmr-server    | AgentGateway
dmr-agent-b   | [Nest] 1  - 07/03/2025, 12:30:14 PM     LOG [WebsocketService] Connected to DMR server with ID: PDU6755A2sHMr9POAAAE +983ms
dmr-agent-b   | [Nest] 1  - 07/03/2025, 12:30:14 PM     LOG [WebsocketService] Recovery state: new connection +0ms
dmr-agent-b   | [Nest] 1  - 07/03/2025, 12:30:14 PM    WARN [WebsocketService] Disconnected from DMR server. Reason: io server disconnect +2ms
```

### PR DESCRIPTION
**Pull request by furqattrade**
What Was Fixed:
MSW Timing - Server initialization order corrected
Race Condition - Initial config sync before accepting connections
Error Handling - Graceful retry mechanism for empty configurations
Agent Reconnection - Manual reconnection on server disconnect
RabbitMQ Setup - Retry mechanism for queue creation
WebSocket Errors - Null pointer protection in AgentGateway

Server logs => everything is clean and working 
image

Agent B
image
Agent A
image

### CODE REVIEW

File: apps/dmr-server/src/main.ts [hunk 1]
```diff
@@ -31,20 +31,20 @@ async function bootstrap(): Promise<void> {
...
     server.listen({
       onUnhandledRequest: 'bypass',
     });
   }
+
+  await app.listen(appConfig.port);
+
+  if (appConfig.environment === 'development') {
+    logger.log(`Listening on ${await app.getUrl()}`);
+  }
```
Comment (IgorKrupenja) [inline apps/dmr-server/src/main.ts:47]: This is very clever, thanks!

**Review by IgorKrupenja — APPROVED** [review]

**Review by IgorKrupenja — APPROVED** [review]
